### ISSUE TITLE
Benchmark publishing

### ISSUE THREAD

**Issue by avaneev** [dynatrace-oss/hash4j#121]
Could you please add a topic on the mainpage that lists benchmark results of all zero-allocation hash functions available? I may be asking for a trouble for komihash, but it would be interesting to know anyway.

**Comment by oertl** [comment]
Since benchmarking in Java is much more complicated than in C/C++ due to just-in-time optimizations by the JVM, we currently do not want to maintain a list of benchmark results. However, there are ideas for a test infrastructure to automatically run benchmarks on different platforms and JVMs in future.

For now, you can execute the corresponding benchmarks by running `./gradlew jmh`. If you are only interested in functions for hashing byte arrays without allocations you could add
```
jmh {
    includes=['com.dynatrace.hash4j.hashing.*hashBytes.*Direct']
}
```
to `build.gradle`.

**Comment by avaneev** [comment]
No problem, thanks!

**Comment by avaneev** [comment]
Thank you. Looks like komihash5 is not that much behind wyhashFinal4. komihash can't be faster due to a bit more complex structure.
